version: "3"
services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "/home/tsuki/volumes/postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "password"
    container_name: reddit-clone-postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: reddit-clone-redis